### ISSUE TITLE
无法读取剪切板图片闪退

### ISSUE THREAD

**Issue by ytf211** [hanxinhao000/ZeroTermux#47]
系统：HyperOS 安卓14

在软件内截图，系统自动将图片写入剪切板，会导致闪退，关闭剪切板读取权限正常

```
- Version:0.118.37.1

java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.ClipData$Item android.content.ClipData.getItemAt(int)' on a null object reference
	at com.termux.zerocore.utils.ClipBoardUtil$1.onPrimaryClipChanged(ClipBoardUtil.java:33)
	at android.content.ClipboardManager.reportPrimaryClipChanged(ClipboardManager.java:467)
	at android.content.ClipboardManager$1.lambda$dispatchPrimaryClipChanged$0(ClipboardManager.java:105)
	at android.content.ClipboardManager$1.$r8$lambda$kJXazWSaZBVUkaNS1pjEccGcb3A(Unknown Source:0)
	at android.content.ClipboardManager$1$$ExternalSyntheticLambda0.run(Unknown Source:2)
	at android.os.Handler.handleCallback(Handler.java:958)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:224)
	at android.os.Looper.loop(Looper.java:318)
	at android.app.ActivityThread.main(ActivityThread.java:8744)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:561)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1013)

```

**Comment by hanxinhao000** [comment]
https://github.com/hanxinhao000/ZeroTermux/releases/tag/release
已修复
